import { request } from '../utils/request';

export const config = (data: any) => request('canteen/config-data', data, 'post')
export const menuList = (data: any) => request('canteen/list', data, 'post')
export const account = (data: any) => request('canteen/account', data, 'post')
export const myorder = (data: any) => request('canteen/my-order', data, 'post', true)
export const rechargelog = (data: any) => request('canteen/recharge-log', data, 'post')
export const refundlog = (data: any) => request('canteen/refund-log', data, 'post')
export const sellOrder = (data: any) => request('canteen/sell-order', data, 'post')
export const closeOrder = (data: any) => request('canteen/close-order', data, 'post')
export const shareOrder = (data: any) => request('canteen/share-order', data, 'post')
export const weixinRecharge = (data: any) => request('weixin-pay/shitang-recharge', data, 'post')
export const weixinPaySign = (data: any) => request('weixin-pay/sign', data, 'post')
export const weixinPaySuccess = (data: any) => request('weixin-pay/shitang-success', data, 'post')
export const weixinPayCancel = (data: any) => request('weixin-pay/shitang-cancel', data, 'post')
export const saveOrder = (data: any) => request('canteen/save-order', data, 'post')
export const orderInfoData = (data: any) => request('canteen/order-info', data, 'post', true)
export const receiveOrder = (data: any) => request('canteen/receive-order', data, 'post')
export const useOrder = (data: any) => request('canteen/use-order', data, 'post')
export const menuInfo = (data: any) => request('canteen/menu-info', data, 'post')
export const menuLike = (data: any) => request('canteen/menu-like', data, 'post')
export const commentData = (data: any) => request('canteen/comment-list', data, 'post')
export const commentSave = (data: any) => request('canteen/comment-save', data, 'post')
export const commentDelete = (data: any) => request('canteen/comment-delete', data, 'post')
export const DayOrderSum = (data: any) => request('canteen/day-order-sum', data, 'post', true)
export const popNotice = (data: any) => request('canteen-vote/check', data, 'post')
export const popNoticeState = (data: any) => request('canteen-vote/state', data, 'post')
export const tvMenuNum = (data: any) => request('canteen-screen/menu-num', data, 'post')
export const tvOrderCount = (data: any) => request('canteen-screen/order-count', data, 'post')
export const getH5PayUrl = (data: any) => request('weixin-pay/get-h5-pay-url', data, 'post')
export const popNoticeInfo = (data: any) => request('canteen-vote/info', data, 'post')
export const popVoteSave = (data: any) => request('canteen-vote/save', data, 'post')
export const popVoteResult = (data: any) => request('canteen-vote/result', data, 'post')